mice:
  - 1
  - 2
  - 3


alpha: 
  - 0.75
  - 0.9
  # - 0.95

max_cand: 100

niter: 15

threshold: 0.05

nworkers: 5
ntrees: 10

nrestarts: 10

mu: 0.05
sigma: 0.025

jump_prob: 0.25

mode:
  # - refine
  - refine_ilp

#search parameters
search_timeout: 1.5