site_name: TRIBAL
repo_url: https://github.com/elkebir-group/TRIBAL
theme:
  name: material
  language: en
  navigation_depth: 5
  collapse_navigation: False
  sticky_navigation: True
  locale: en
  titles_only: False
  logo: img/logo.png
  font:
    code: Roboto Mono
  features:
    - navigation.tabs 
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.path
    - toc.integrate
    - toc.collapsible
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  palette:
    primary: brown
    accent: deep purple
  # extra_css:
  #   - css/logo.css
    # theme:
      # - scheme: default
      #   toggle:
      #     icon: material/brightness-7 
      #     name: Switch to dark mode
      # - scheme: slate
      #   toggle:
      #     icon: material/brightness-4
      #     name: Switch to light mode
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          docstring_style: numpy
        rendering:
          show_source: true
- search
markdown_extensions:
  - def_list
  - sane_lists
  # - smarty
  - toc:
      baselevel: 1
      toc_depth: 1-4
      permalink: True
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - tables

docs_dir: 'docs'
nav:
  - 'About' : index.md
  - 'Usage': 
      - 'Download & Installation': setup/install.md
      - 'Data' : setup/data.md
      - 'Package Overview' : setup/package.md
      - 'Command Line Interface' : setup/cli.md
  - 'API':
      - 'Preprocesssing': 'api/preprocess.md'
      - 'BaseTree': 'api/base_tree.md'
      - 'Clonotype': 'api/clonotype.md'
      - 'Tribal': 'api/tribal.md'
      - 'LineageTree': 'api/lineagetree.md'
      - 'LineageTreeList': 'api/lineagetreelist.md'

# site_name: TRIBAL
# # site_url: https://dowser.readthedocs.io
# repo_url: https://github.com/elkebir-group/TRIBAL
# # edit_uri: src/master/docs/
# theme:
#   # name: readthedocs
#   name: material
#   navigation_depth: 4
#   collapse_navigation: False
#   sticky_navigation: True 
#   locale: en
#   titles_only: False
#   logo: img/logo.png
#   features:
#     - navigation.tabs 
#     - navigation.sections
#     - navigation.top
#     - toc.integrate
#     - search.suggest
#     - content.code.annotation
#     - content.code.copy
#     - content.tabs.link
#   palette:
#     primary: deep purple
#     accent: deep orange
#     theme:
#     # Palette toggle for light mode
#     - scheme: default
#       toggle:
#         icon: material/brightness-7 
#         name: Switch to dark mode

#     # Palette toggle for dark mode
#     - scheme: slate
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode
# language: en

# plugins:
#   - search
#   - mkdocstrings:
#       handlers:
#         python:
#           docstring_style: numpy
#           options:
#             show_source: true
#           #   selection:
#           #     members:
#           #       - "!^_"  # Exclude private members starting with an underscore
# markdown_extensions:
#   - def_list
#   - sane_lists
#   - smarty
#   - toc:
#       baselevel: 1
#       toc_depth: 1-6
#       permalink: True
#   - admonition
#   - pymdownx.snippets
#   - pymdownx.details
#   - codehilite
#   - pymdownx.superfences
#   - pymdownx.tabbed
#   - pymdownx.details
# docs_dir: 'docs'
# nav:
#   - 'About' : index.md
#   - 'Getting Started': 
#     - 'Download & Installation': setup/install.md
#     - 'Package Overview' : setup/package.md
#     - 'Command Line Interface' : setup/cli.md
#   - 'API':
#     - 'Preprocesssing': 'api/preprocess.md'
#     - 'BaseTree': 'api/base_tree.md'
#     - 'Clonotype': 'api/clonotype.md'
#     - 'Tribal': 'api/tribal.md'
#     - 'LineageTree': 'api/lineagetree.md'
#     - 'LineageTreeList': 'api/lineagetreelist.md'


# nav:
#   - 'Immcantation Portal': https://immcantation.readthedocs.io/
#   - 'About':
#     - 'Introduction': index.md
#     - 'Download & Installation': install.md
#     - 'Package Overview': topics/dowser.md
#     - 'Release Notes': news.md
#     - 'Related Projects': projects.md
#   - 'Vignettes':
#     - 'Quickstart': vignettes/Quickstart-Vignette.md
#     - 'Reconstruct clonal germlines': vignettes/Germlines-Vignette.md
#     - 'Build lineage trees': vignettes/Building-Trees-Vignette.md
#     - 'Plot lineage trees': vignettes/Plotting-Trees-Vignette.md
#     - 'Heavy+light chain tree building': vignettes/Resolve-Light-Chains-Vignette.md
#     - 'Reconstruct intermediate sequences': vignettes/Sequences-Vignette.md
#     - 'Detecting evolution over time': vignettes/Measurable-Evolution.md
#     - 'Migration, differentiation, and isotype switching': vignettes/Discrete-Trait-Vignette.md
#   - 'Function Documentation':
#     #- 'Germline construction functions':
#     - topics/readIMGT.md
#     - topics/createGermlines.md
#     #- 'Clone formating functions':
#     - topics/formatClones.md
#     - topics/makeAirrClone.md
#     - topics/airrClone-class.md
#     - topics/resolveLightChains.md
#     #- 'Tree building functions':
#     - topics/getTrees.md
#     - topics/buildIgphyml.md
#     - topics/buildPML.md
#     - topics/buildPhylo.md
#     - topics/buildPratchet.md
#     - topics/buildRAxML.md
#     #- 'Visualization functions':
#     - topics/plotTrees.md
#     - topics/treesToPDF.md
#     - topics/colorTrees.md
#     - topics/getPalette.md
#     - topics/collapseNodes.md
#     - topics/scaleBranches.md
#     - topics/rerootTree.md
#     #- 'Intermediate sequence functions':
#     - topics/getNodeSeq.md
#     - topics/getSubTaxa.md
#     #- 'Discrete trait analysis functions':
#     - topics/findSwitches.md
#     - topics/testPS.md
#     - topics/testSC.md
#     - topics/testSP.md
#     #- 'Tree based statitsitcs':
#     - topics/calcRF.md
#     - topics/correlationTest.md
#     - topics/getBootstraps.md
#     - topics/getDivergence.md