
#changed to set the name of the dataset to be run
dataset: GCB_NP_1






#TRIBAL parameters

lamb: 0.75


ntrees: 
  - 10


max_cand:
  -50

niter:
  - 20

nworkers: 5
nrestarts: 5
mu: 0.075
sigma: 0.05

seed:
  - 3

threshold: 0.1

search_timeout: 4


jump_probs: 
  - 0.25
