seq:
  - heavy
  - light

run_dir:
  - day_14
  # - GCB_NP_1
  # - GCB_NP_2
  # - GCB_OVA_1



# clono_file:
#   - "/scratch/projects/tribal/real_data/day_14/clonotype_summary.csv"

clono_file:
  day_14: 
    - "/scratch/projects/tribal/real_data/day_14/clonotype_summary.csv"
  GCB_NP_1:
    - "/scratch/projects/tribal/real_data/GCB_NP_1/clonotype_summary.csv"
  GCB_NP_2: 
    - "/scratch/projects/tribal/real_data/GCB_NP_2/clonotype_summary.csv"
  GCB_OVA_1: 
    - "/scratch/projects/tribal/real_data/GCB_OVA_1/clonotype_summary.csv"
#tribal params
#tribal params
alpha:
  - 0.75
  # - 0.9

max_cand:
  -50

niter:
  - 20

nworkers: 5
nrestarts: 5
mu: 0.075
sigma: 0.05

seed:
  - 3

threshold:
  - 0.1

search_timeout: 8

jump_probs:
  - 0.25
  - 0.2
  - 0.1
  - 0.35