
#sim parameters

size: 
  - 75
ncells: 
  - 65

rep: 1

ttype:
  - direct 
  - seq
#tribal parameters

lamb: 3.5

nreps: 20

alpha: 
  - 0.75
  # - 0.9
  # - 0.95

max_cand: 25

niter: 20

threshold: 0.1

nworkers: 5
ntrees: 10

nrestarts: 5

mu: 0.05
sigma: 0.025

jump_prob: 0.25


#search parameters
search_timeout: 1.5